Configuração da esteira e da página

diff --git a/.github/workflows/docker.yml b/.github/workflows/docker.yml
--- a/.github/workflows/docker.yml
+++ b/.github/workflows/docker.yml
@@ -14,11 +14,25 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v3
 
+      - name: Debug Secrets
+        run: |
+          echo "Username: ${{ secrets.DOCKERHUB_USERNAME }}"
+          echo "Token length: ${{ secrets.DOCKERHUB_TOKEN != '' && 'Token is set' || 'Token is empty' }}"
+
       - name: Login to Docker Hub
         run: |
-          docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
-
+            if [[ -z "${{ secrets.DOCKERHUB_USERNAME }}" || -z "${{ secrets.DOCKERHUB_TOKEN }}" ]]; then
+              echo "Docker Hub credentials are missing. Please set them in the repository secrets."
+              exit 1
+            fi
+            docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_TOKEN }}"
+      
       - name: Build and push Docker image
         run: |
+<<<<<<< HEAD
+          docker buildx build -t camileite/gelatosavelas:${GITHUB_SHA} .
+          docker push camileite/gelatosavelas:${GITHUB_SHA} 
+=======
           docker buildx build -t camileite/mriaas:${{ github.sha }} .
           docker push camileite/mriaas:${{github.sha}} 
+>>>>>>> de67030fe2efc967c38ca8db611987581b78a8d2
